"""Pydantic schemas for the CEO Planning and Orchestration layer."""

from typing import Any, Literal

from pydantic import BaseModel, Field


class GoalIntake(BaseModel):
    """Structured input model for CEO goal intake."""

    objective: str = Field(
        ..., min_length=3, max_length=2000, description="Primary goal or objective to accomplish"
    )
    requested_outcome: str | None = Field(
        default=None, max_length=2000, description="Desired concrete outcome or deliverable"
    )
    constraints: list[str] = Field(
        default_factory=list, description="User or policy constraints on execution"
    )
    priority: Literal["low", "medium", "high", "critical"] = Field(
        default="medium", description="Priority level of the goal"
    )
    requirements: list[str] = Field(default_factory=list, description="Explicit user requirements")


class PlanStep(BaseModel):
    """A discrete node in the proposed plan task graph."""

    step_id: str = Field(
        ..., min_length=1, max_length=64, description="Stable identifier for the step (e.g. step_1)"
    )
    title: str = Field(
        ..., min_length=1, max_length=255, description="Short title describing the step"
    )
    description: str = Field(..., description="Detailed description of the proposed work")
    assigned_agent_id: str | None = Field(
        default=None, description="ID of the registered agent assigned to this step"
    )
    assigned_agent_role: str = Field(
        ..., description="Organizational role responsible for this step (e.g. cmo, cto)"
    )
    department_code: str | None = Field(
        default=None, description="Department code associated with the step"
    )
    depends_on: list[str] = Field(
        default_factory=list, description="List of step_ids that must complete before this step"
    )
    required_capabilities: list[str] = Field(
        default_factory=list, description="Declared capabilities needed for this step"
    )
    expected_output: str = Field(..., description="Expected tangible deliverable from this step")
    verification_criteria: str = Field(
        ..., description="How success and completion are objectively verified"
    )


class DelegationProposal(BaseModel):
    """Typed proposal for delegating work to a registered agent."""

    proposal_id: str = Field(..., description="Unique identifier for the delegation proposal")
    source_agent_id: str | None = Field(default=None, description="ID of delegating agent (CEO)")
    target_agent_id: str | None = Field(
        default=None, description="ID of registered agent receiving delegation"
    )
    target_role: str = Field(..., description="Target role (e.g. cto, cmo, software_architect)")
    objective: str = Field(..., description="Specific objective delegated to the target")
    scope: str = Field(..., description="Boundaries and scope of the delegated work")
    expected_output: str = Field(..., description="Expected output from target agent")
    required_capabilities: list[str] = Field(
        default_factory=list, description="Declared capabilities needed"
    )
    constraints: list[str] = Field(
        default_factory=list, description="Constraints specific to this delegation"
    )
    authority_level_required: int = Field(
        default=1, ge=1, le=5, description="Required authority level (1-5)"
    )


class ApprovalRequirement(BaseModel):
    """Action or step within a plan that requires governance approval."""

    step_id: str = Field(..., description="Associated step identifier")
    action_description: str = Field(..., description="Description of the action requiring approval")
    risk_level: Literal["low", "medium", "high", "critical"] = Field(
        default="medium", description="Evaluated risk level"
    )
    reason_for_approval: str = Field(
        ..., description="Why governance or human approval is mandatory"
    )


class PlanResult(BaseModel):
    """Structured plan output generated by the planning engine."""

    goal: str = Field(..., description="Original goal statement")
    reasoning_summary: str = Field(
        ..., description="Audit-safe, concise reasoning summary explaining the plan breakdown"
    )
    steps: list[PlanStep] = Field(
        default_factory=list, description="Ordered nodes of the task graph"
    )
    delegation_proposals: list[DelegationProposal] = Field(
        default_factory=list, description="Typed delegation proposals"
    )
    approval_requirements: list[ApprovalRequirement] = Field(
        default_factory=list, description="Explicit approval gates"
    )
    risks: list[dict[str, Any]] = Field(
        default_factory=list, description="Identified execution risks and mitigations"
    )
    assumptions: list[str] = Field(
        default_factory=list, description="Planning assumptions made during decomposition"
    )
