"""create agent registry

Revision ID: 0004_create_agent_registry
Revises: 0003_create_companies_and_org
Create Date: 2026-09-21 03:07:15.866566

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0004_create_agent_registry"
down_revision: str | Sequence[str] | None = "0003_create_companies_and_org"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agents",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("company_id", sa.String(length=36), nullable=False),
        sa.Column("department_id", sa.String(length=36), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=128), nullable=False),
        sa.Column("type", sa.String(length=64), server_default="specialist", nullable=False),
        sa.Column("reports_to", sa.String(length=36), nullable=True),
        sa.Column("mission", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=32), server_default="active", nullable=False),
        sa.Column(
            "authority_level", sa.String(length=64), server_default="specialist", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["department_id"], ["departments.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["reports_to"], ["agents.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_agents_company_department", "agents", ["company_id", "department_id"], unique=False
    )
    op.create_index(op.f("ix_agents_company_id"), "agents", ["company_id"], unique=False)
    op.create_index("ix_agents_company_status", "agents", ["company_id", "status"], unique=False)
    op.create_index(op.f("ix_agents_department_id"), "agents", ["department_id"], unique=False)
    op.create_index(op.f("ix_agents_reports_to"), "agents", ["reports_to"], unique=False)
    op.create_table(
        "agent_definitions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("agent_id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.String(length=32), server_default="1.0", nullable=False),
        sa.Column("system_prompt", sa.Text(), nullable=True),
        sa.Column("model", sa.String(length=128), server_default="gemini-1.5-pro", nullable=False),
        sa.Column("capabilities", sa.JSON(), server_default="[]", nullable=False),
        sa.Column("tools", sa.JSON(), server_default="[]", nullable=False),
        sa.Column("configuration", sa.JSON(), server_default="{}", nullable=False),
        sa.Column("is_current", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["agent_id"], ["agents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("agent_id", "version", name="uq_agent_definitions_agent_version"),
    )
    op.create_index(
        "ix_agent_definitions_agent_current",
        "agent_definitions",
        ["agent_id", "is_current"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_definitions_agent_id"), "agent_definitions", ["agent_id"], unique=False
    )
    op.create_index(
        op.f("ix_agent_definitions_is_current"), "agent_definitions", ["is_current"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_agent_definitions_is_current"), table_name="agent_definitions")
    op.drop_index(op.f("ix_agent_definitions_agent_id"), table_name="agent_definitions")
    op.drop_index("ix_agent_definitions_agent_current", table_name="agent_definitions")
    op.drop_table("agent_definitions")
    op.drop_index(op.f("ix_agents_reports_to"), table_name="agents")
    op.drop_index(op.f("ix_agents_department_id"), table_name="agents")
    op.drop_index("ix_agents_company_status", table_name="agents")
    op.drop_index(op.f("ix_agents_company_id"), table_name="agents")
    op.drop_index("ix_agents_company_department", table_name="agents")
    op.drop_table("agents")
    # ### end Alembic commands ###
